config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end

  resources :posts, only: [:new] do
    resources :comments, only: [:create]
    resources :likes, only: [:create]
  end

  post '/posts/new', to: 'posts#create', as: 'create_post'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts_counter

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, inverse_of: :author, foreign_key: :author_id
  has_many :likes, inverse_of: :author, foreign_key: :author_id
  has_many :posts, inverse_of: :author, foreign_key: :author_id
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
    @user = @post.author
  end

  def create
    @comment = Comment.new(comments_params)
    @comment.author = current_user
    @comment.post = Post.find(params[:post_id])
    if @comment.save
      redirect_to user_post_path(@comment.post.author, @comment.post)
    else
      render :new
    end
  end

  private

  def comments_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.author = current_user
    @like.post = Post.find(params[:post_id])
    if @like.save
      redirect_to user_post_path(@like.post.author, @like.post)
    else
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find_by(id: params[:user_id])
    render file: "#{Rails.root}/public/404.html", status: :not_found, layout: false if @user.nil?
    @posts = @user.posts.includes(comments: :author)
    render :index, locals: { user: @user, posts: @posts }
  end

  def show
    @post = Post.find_by(author_id: params[:user_id], id: params[:id])
    render file: "#{Rails.root}/public/404.html", status: :not_found, layout: false if @post.nil?

    @comments = @post.comments
    @user = @post.author
    render :show, locals: { post: @post, comments: @comments, user: @user }
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    if @post.save
      redirect_to user_post_path(current_user, @post)
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
    if @user.nil?
      render file: "#{Rails.root}/public/404.html", status: :not_found, layout: false
    else
      @posts = @user.posts
      render :show, locals: { user: @user, posts: @posts }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<% truncate = false unless defined? truncate %>

<li class="card m-3">
  <div class="card-body">
    <h5 class="card-title"><%= comment.author.name %></h5>
    <% comment_text = comment.text || '...' %>
    <p class="card-text"><%= truncate ? comment_text.truncate(100) : comment_text %></p>
  </div>
</li>

app/views/comments/new.html.erb
<%= render @post, locals: {show_comments: false} %>

<h1 class="row align-items-center justify-content-center m-5">Comment</h1>

<div class="card h-100" style="background-color: #5a5a5a; text-align: center;">
  <%= form_with model: @comment, url: post_comments_path(@post) do |form| %>
    <div class="card-header">
      Comment
    </div>
    <div class="card-body">
      <%= form.text_area :text, class: "form-control", rows: "15" %>
    </div>
    <div class="card-footer">
      <%= form.submit "Comment", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,300;1,400;1,700&family=Lobster&display=swap" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
      tailwind.config = {
        theme: {
          extend: {
        },
        fontFamily: {
              'sans': ['Inter var'],
              'important': ['Lobster'],
              'type1': ['Josefin Sans'],
          },
      },
          }
    </script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="font-type1 sm:text-lg tracking-wide break-words">
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
# <% truncate = false unless defined? truncate %>
# <% show_comments = true unless defined? show_comments%>

# <li class="card m-3">
#   <%= link_to user_post_path(@user, post), class: "text-decoration-none card-body", style: "color: #000" do %>
#     <h5 class="card-title"><%= post.title %></h5>
#     <% post_text = post.text || '...' %>
#     <p class="card-text"><%= truncate ? post_text.truncate(100) : post_text %></p>
#   <% end %>
#   <span class="ms-auto">Comments: <%= post.comments_counter %> | Likes: <%= post.likes_counter %></span>
# </li>

# <% if show_comments %>
#   <ul class="col p-0">
#     <%= render post.comments, locals: {truncate: truncate} %>
#   </ul>
# <% end %>

app/views/posts/index.html.erb
<section id="posts" class="md:m-10 m-2 flex gap-5 flex-col">
<div class="posts-header">
  Here is a list of posts for a given user
</div>
     <div class="user h-full flex h-full gap-2 sm:gap-7 p-3">
        <div class="sm:max-h-[200px] sm:max-w-[200px] max-h[100px] max-w-[100px] object-cover">
            <img class="rounded-xl h-full w-gull object-cover" alt="user-<%= @user.id%>" src="https://images.unsplash.com/photo-1508921912186-1d1a45ebb3c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80">
        </div>
        <div class="col-span-5 flex-1 p-3 flex flex-col gap-2">
            <h2 class="font-important tracking-widest text-lg font-semibold"><%= @user.name %></h2>
         <div class="flex flex-col justify-between flex-wrap">
            <span class="float-left">Total Posts: <span><%= @user.posts_counter%></span></span>
            </div>
        </div>
      </div>
      <ul class="grid grid-cols-1 gap-5" id="posts-container">
        <% @posts.each do |post|%>
          <li>
           <div>
             <a href="/users/<%= @user.id%>/posts/<%=post.id%>" class="grid grid-cols-1 gap-2 hover:bg-slate-300 p-3 rounded-lg">
              <h3 class="font-important text-lg font-semibold tracking-wider"><%= post.title%></h3>
            <p class="pt-4 break-words"><%= post.text.truncate(100) %></p>
            <span class="flex justify-end">Comments: <%= post.comments_counter%>  Likes: <%= post.likes_counter%> </span>
            </a>
           </div>
            <div>
                <% unless post.comments.length == 0%>
                    <h3 class="font-thin tracking-wider font-important my-3 mx-3">Comments</h3>
                <%end%>
                <ul class="flex gap-3 flex-col px-5 my-3">
                <% post.recent_comments.each do |comment|%>
                    <li class="flex flex-col gap-2 p-2 border-l border-red-200 hover:bg-red-300">
                        <a class="text-sm sm:text-base hover:underline hover:font-bold" href="/users/<%= comment.author.id%>"><%= comment.author.name%>: </a>
                        <span class="sm:text-base text-sm pl-5 break-words"><%= comment.text%></span>
                    </li>
                <%end%>
                </ul>
            </div>

          </li>
        <% end %>
      </ul>
<section>

app/views/posts/new.html.erb
<h1 class="row align-items-center justify-content-center m-5">Create a Post</h1>

<div class="card h-100 " style="background-color: #5a5a5a; text-align: center;">
  <%= form_with model: @post do |form| %>
    <div class="card-header">
      <%= form.text_field :title, class: "form-control", placeholder: "Post's title" %>
    </div>
    <div class="card-body">
      <%= form.text_area :text, class: "form-control", rows: "10" %>
    </div>
    <div class="card-footer">
      <%= form.submit "Create", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<section id="post" class="md:m-10 m-2 flex gap-5 flex-col">
    <div>
      <div class="flex flex-col gap-3 py-3 px-6 border border-red-300" id="post-section">
      <div class="d-flex col p-2">
      <%= link_to "Comment", new_post_comment_path(post), class: "btn btn-primary me-2" %>
      <%= form_with url: post_likes_path(post) do |form| %>
        <%= form.submit "Like", class: "btn btn-secondary" %>
      <% end %>
      <span class="ms-auto">Comments: <%= post.comments_counter %> | Likes: <%= post.likes_counter %></span>
    </div>
        <div>
            <h2 class="px-2 break-words"><%= @post.text%></h2>
        </div>
      </div>
      <div class="" id="comment-section">
         <div>
            <h3 class="font-thin tracking-wider font-important my-3">Comments</h3>
                <ul class="flex gap-3 flex-col px-5 my-3">
                <% post.comments.each do |comment|%>
                    <li class="flex flex-col gap-2 p-2 border-l border-red-200 hover:bg-red-300">
                        <a class="text-sm sm:text-base hover:underline hover:font-bold" href="/users/<%= comment.author.id%>"><%= comment.author.name%>: </a>
                        <span class="sm:text-base text-sm pl-5"><%= comment.text%></span>
                    </li>
                <%end%>
                </ul>
            </div>
        </div>
    </div>
</section>

app/views/users/_user.html.erb
# <li class="card m-3">
#   <%= link_to user_path(user), class: "card-body row text-decoration-none", style: "color: #000" do %>
#     <%= image_tag user.photo, class: "col-2 img-fluid img-thumbnail", style: "aspect-ratio: 1" if user.photo %>
#     <div class="d-flex col-10 p-3">
#       <h2 class="my-auto"><%= user.name %></h2>
#       <span class="ms-auto mt-auto">Number of posts: <%= user.posts_counter %></span>
#     </div>
#   <% end %>
# # </li>

app/views/users/index.html.erb
<section class="" id="users">
<div class="row justify-content-end">
<%= link_to "Create Post", new_post_path, class: "btn btn-primary" %>
</div>
  <ul class="sm:m-10 m-2 grid grid-cols-1 gap-10">
    <% @users.each do |user|%>
      <li class="user h-full">
        <a href="/users/<%= user.id%>" class="flex h-full gap-7 p-3 hover:bg-slate-300 rounded-lg">
            <div class="max-h-[200px] min-h[100px] min-w-[100px] max-w-[100px] object-cover">
            <img class="rounded-xl max-h-[130px] w-[100px] object-cover" alt="user-<%= user.id%>" src='<%=user.photo%>'>
        </div>
        <div class="col-span-5 flex-1 p-3 flex flex-col gap-2">
            <h2 class="font-important tracking-wider text-lg font-semibold"><%= user.name %></h2>
            <p class="font-type1 max-h-[70px] text-ellipsis break-words"><%= user.bio&.truncate(40)%></p>

         <div class="flex justify-between flex-wrap">
               <span>Last seen:<span></span></span>
            <span class="float-left">Number of Posts: <span><%= user.posts_counter%></span></span>
            </div>
        </div>

        </a>
        
      </li>
    <% end %>
  </ul>
</section>

app/views/users/show.html.erb
<section id="user" class="md:m-10 m-2 flex gap-5 flex-col">
<div class="posts-header">
User details
</div>
  <div class="user h-full flex h-full gap-2 sm:gap-7 p-3">
    <div class="sm:max-h-[200px] sm:max-w-[200px] max-h[100px] max-w-[100px] object-cover">
      <img class="rounded-xl h-full w-gull object-cover" alt="user-<%= @user.id%>" src="<%=@user.photo%>">
    </div>
    <div class="col-span-5 flex-1 p-3 flex flex-col gap-2">
      <h2 class="tracking-wider font-important text-lg font-semibold"><%= @user.name %></h2>
      <div class="flex flex-col justify-between flex-wrap">
        <span>Last seen:<span></span></span>
        <span class="float-left">Total Posts: <span><%= @user.posts_counter%></span></span>
      </div>
    </div>
  </div>
  <div class="hover:bg-slate-300 rounded-lg p-3">
    <h2 class="tracking-wider font-important text-lg font-semibold">Bio</h2>
    <p class="font-type1 max-h-[70px] text-ellipsis overflow-hidden"><%= @user.bio%></p>
  </div>
  <ul class="grid grid-cols-1 gap-5" id="posts-container">
    <% @user.recent_posts.each do |post|%>
      <li>
        <a href="/users/<%= @user.id%>/posts/<%=post.id%>" class="grid grid-cols-1 gap-2 hover:bg-slate-300 p-3 rounded-lg">
          <h3 class="tracking-wider font-important text-lg font-semibold"><%= post.title%></h3>
          <p class="pt-4 break-words"><%= post.text.truncate(100) %></p>
          <span class="flex justify-end">Comments: <%= post.comments_counter%>  Likes: <%= post.likes_counter%> </span>
        </a>
      </li>
    <% end %>
  </ul>
  <% if @posts && @posts.length > 3%>
    <div class="flex justify-around text-center items-center">
      <button onclick="show(event,'<%= @posts.to_json%>')" id="load-more-posts" type="button" class=" p-2 hover:bg-black hover:text-red-400 rounded-lg tracking-wider font-important text-lg font-semibold">Load More</button>
      <a href='/users/<%=@user.id%>/posts' class="p-2 hover:bg-black hover:text-red-400 rounded-lg tracking-wider font-important text-lg font-semibold">See All Posts</a>
    </div>
  <%end%>
  <section>
    <script>
      const loadMoreBtn = document.getElementById('load-more-posts');
      let isShowingAllPosts = false;

      const renderPosts = (postsToRender) => {
          const postsContainer = document.querySelector('#posts-container');
          postsToRender.forEach((post) => {
            const postElement = document.createElement('li');
            console.log(post)
            postElement.innerHTML = `<a href="/users/${post.author_id}/posts/${post.id}" class="grid grid-cols-1 gap-2 hover:bg-slate-300 p-3 rounded-lg">
            <h3 class="tracking-wider font-important text-lg font-semibold">${post.title}</h3>
            <p class="pt-4">${post.text}</p>
            <span class="flex justify-end">Comments: ${post.comments_counter}  Likes: ${post.likes_counter} </span>
            </a>`;
          postsContainer.appendChild(postElement);
        });
      }

      const showPosts = (postsArray) => {
            const postsToRender = postsArray.slice(3);
            renderPosts(postsToRender);
            loadMoreBtn.innerText = 'Hide posts';
      }

      const hidePosts = (postsArray) => {
        const postsContainer = document.querySelector('#posts-container');
        postsContainer.innerHTML = '';
        const postsToRender = postsArray.slice(0, 3);
        renderPosts(postsToRender);
        loadMoreBtn.innerText = 'Load More';
      }

       window.show = (event, posts) => {
      event.preventDefault();
      const postsContainer = document.querySelector('#posts-container');
      const postsArray = JSON.parse(posts);
      if (isShowingAllPosts) {
        hidePosts(postsArray);
        isShowingAllPosts = false;
        return;
      }
      showPosts(postsArray);
      isShowingAllPosts = true;
      }
    </script>